### ISSUE TITLE
Ce face pluginul ?

### ISSUE THREAD

**Issue by giucu91** [WPChill/dlm-migrate-download-counts#1]
Cand instalezi pluginul o sa iti apara un notice care va fi pe toate paginile. Noticeul va avea titlu / descriere / 1 buton

Butonul: sync manual counts with reports
- va lua toate logurile din tabela reports `SELECT count(download_id), download_id FROM ' . $wpdb->download_log . " GROUP BY download_id LIMIT -1`
- pentru fiecare download returnat din tabela de reports se va verifica post meta si daca e mai mare se va scadea countul din reports si se va actualiza post meta

**Comment by razvanaldea89** [comment]
Ar trebui sa fie luata pe bucati informatia pentru a nu da eroare de time limit sau memory limit. @TeoAlex te poti uita la cum e facut in rapoarte.
